### ISSUE TITLE
Explore native app generation

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-template-javafx#5]
Is it feasible / recommended to create a native app via graalvm?

- [x] decision whether to go with native apps or not is discussed and taken

**Comment by FDelporte** [comment]
Can't be a coincidence, just today I got the same question of Jakob Jenkov if it is possible to generate native apps with GraalVM on Raspberry Pi for this tutorial https://jenkov.com/tutorials/graalvm/index.html

My (limited) experience in this topic: tried and failed ;-) 
But that was because I was doing it with a 32bit OS which is (still?) not supported by GraalVM.

Next challenge is the amount of memory needed to compile: a similar attempt was made by https://github.com/aero-don/micronaut-pi4j-minimal-example

From the README:

_The native image build requires approximately 8 GB of RAM to execute. An attempt to execute the native image build on a Raspberry Pi 4B with 4GB RAM resulted in the build exiting with an error code of 137 Out of Memory._
 
_Oracle Cloud Infrastructure offers an ARM compute instance. The Oracle Cloud Free Tier offers an Ampere A1 Compute instance with up to 4 cores and up to 24 GB RAM for free. The native image successfully built with 3 cores and 16 GB ram in a little over 3 minutes._

**Comment by DieterHolz** [comment]
A feasible way could be to let it create by github-actions.

We can use our JavaFX-support-license to get support from Gluon

**Comment by eitch** [comment]
I would have enough compute resources to build this, i just have no idea how. Is there a docker container i could use for that?

**Comment by DieterHolz** [comment]
template project already used the gluonfx-plugin.

This could be a starting point

https://docs.gluonhq.com/#_configuration
